matrix:
  include:
    - language: python
      python:
        - "3.7-dev"
      cache: pip
      install:
        - pip install requirements-dev.txt
      script:
        - pytest --cov-report term --cov=./backend backend/tests
      after_success:
        - codecov

    - language: node_js
      node_js:
        - "11.10.0"
      cache: npm
      install:
        - npm install
      script:
        - npm run test
      after_success:
        - npm run codecov
