matrix:
  include:
    - language: python
      python:
        - "3.7.2"
      before_install:
        - cd backend/
      install:
        - pip install pipenv
        - pipenv install
      script:
        - pipenv run pytest tests
