matrix:
  include:
    - language: python
      python:
        - "3.7-dev"
      before_install:
        - cd backend/
      install:
        - pip install pipenv
        - pipenv install --dev
      script:
        - pipenv run pytest --cov-report term --cov=./ tests
      after_success:
        - pipenv run codecov

    - language: node_js
      node_js:
        - "11.10.0"
      before_install:
        - cd frontend/
      install:
        - npm install
      script:
        - npm run test
